In [130]:
import pandas as pd
import numpy as np

In [131]:
# pd.set_option('display.max_rows', 10) # custom setting pandas

In [132]:
# cotigories - состоит из ограниченного набора значений 
sp = ['name', 'age', 'value', 'value']
cat1 = pd.Categorical(sp)

In [133]:
dir(cat1)

['T',
 '__abstractmethods__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__pyx_vtable__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__setstate_cython__',
 '__sizeof__',
 '__slots__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_accessors',
 '_accumulate',
 '_box_func',
 '_can_hold_na',
 '_cast_quantile_result',
 '_categories_match_up_to_permutation',
 '_codes',
 '_concat_same_type',
 '_constructor',
 '_dir_additions',
 '_dir_deletions',
 '_dtype',
 '_empty',
 '_encode_with_my_categories',
 '_fill_mask_inplace',
 '_formatter',
 '_from_backing_data',
 '_from_factor

In [134]:
cat1.get_values()

AttributeError: 'Categorical' object has no attribute 'get_values'

In [ ]:
cat1.codes

array([1, 0, 2, 2], dtype=int8)

In [ ]:
ct2 = pd.Categorical(sp, categories=['age','value', 'name'])
ct2

['name', 'age', 'value', 'value']
Categories (3, object): ['age', 'value', 'name']

In [ ]:
ct2.sort_values()

['age', 'value', 'value', 'name']
Categories (3, object): ['age', 'value', 'name']

In [ ]:
# категор. пер. - факторные переменные, которые хранят качевтсвенные данные (не имеют числ. знач или )
cat_series = pd.Series(sp, dtype='category')
cat_series.dtype

CategoricalDtype(categories=['age', 'name', 'value'], ordered=False)

In [ ]:
cat_series1 = pd.Series(sp)
cat_series1_as_cat = cat_series1.astype('category')

In [ ]:
cat_series1.dtype

dtype('O')

In [ ]:
# cat - позволяет работать с атрибутами типа категор.
cat_series1_as_cat.cat.codes

0    1
1    0
2    2
3    2
dtype: int8

In [ ]:
cat_series1_as_cat.cat.add_categories(['sex', 'count', 'test'])

0     name
1      age
2    value
3    value
dtype: category
Categories (6, object): ['age', 'name', 'value', 'sex', 'count', 'test']

In [ ]:
cat_series1_as_cat.cat.rename_categories({'sex': 'error'})

0     name
1      age
2    value
3    value
dtype: category
Categories (3, object): ['age', 'name', 'value']

In [ ]:
cat_series1_as_cat.cat.as_ordered(ordered=True)
#help(cat_series1_as_cat.cat.as_ordered)

In [ ]:
np.random.seed(123)
values = np.random.randint(0, 100, 5)
values

array([66, 92, 98, 17, 83])

In [ ]:
bins = pd.DataFrame({'values': values})
bins['groop'] = pd.cut(values, range(0, 101, 10))

In [ ]:
bins.groop

0     (60, 70]
1    (90, 100]
2    (90, 100]
3     (10, 20]
4     (80, 90]
Name: groop, dtype: category
Categories (10, interval[int64, right]): [(0, 10] < (10, 20] < (20, 30] < (30, 40] ... (60, 70] < (70, 80] < (80, 90] < (90, 100]]

In [ ]:
cat_metal = pd.Categorical(["bronze", "gold", "silver", "bronze"], categories=["bronze", "gold", "silver"], ordered=True)

In [ ]:
dir(cat_metal)

In [ ]:
cat_metal.codes

array([0, 1, 2, 0], dtype=int8)

In [ ]:
cat_metal.dtype

AttributeError: 'Categorical' object has no attribute 'get_values'

In [ ]:
cat_metal.categories

Index(['bronze', 'gold', 'silver'], dtype='object')

In [ ]:
remove_bronze = cat_metal.remove_categories(['bronze'])
remove_bronze = remove_bronze.add_categories('uran')
remove_bronze.remove_unused_categories()

[NaN, 'gold', 'silver', NaN]
Categories (2, object): ['gold' < 'silver']

In [ ]:
sr = pd.Series(['cat1', 'cat2', 'cat3'], dtype='category')
sr

0    cat1
1    cat2
2    cat3
dtype: category
Categories (3, object): ['cat1', 'cat2', 'cat3']

In [ ]:
sr.cat.set_categories(['abc', 'dfg'])

0    NaN
1    NaN
2    NaN
dtype: category
Categories (2, object): ['abc', 'dfg']

In [ ]:
sr.describe()

count        3
unique       3
top       cat1
freq         1
dtype: object

In [ ]:
sr.info()

<class 'pandas.core.series.Series'>
RangeIndex: 3 entries, 0 to 2
Series name: None
Non-Null Count  Dtype   
--------------  -----   
3 non-null      category
dtypes: category(1)
memory usage: 267.0 bytes


In [ ]:
np.random.seed(123)
names = ['max', 'ruslan', 'polina']
greads = np.random.randint(50, 101, len(names))

In [ ]:
df_scores = pd.DataFrame({'name': names, 'greads': greads})
score_bins = [2,3,5]
latter_greads = ['f', 'c', 'a']

In [136]:
latter_cut = pd.cut(df_scores, score_bins, labels=latter_greads)
df_scores['LATTER'] = latter_cut

ValueError: Input array must be 1 dimensional

In [ ]:
df_scores

name  greads
0     max      95
1  ruslan      52
2  polina      78